baseURL      = "https://masa162.github.io/garden-archive/"
languageCode = "en-us"
title        = "Garden Archive"
theme        = "PaperMod"

# ↓記事一覧に採用するセクション。PaperMod では推奨
mainSections = ["posts"]
[pagination]
  pagerSize = 10 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true      # 生 HTML を許可
