baseURL      = "https://masa162.github.io/garden-archive/"
languageCode = "en-us"
title        = "Garden Archive"
theme        = "PaperMod"

# ↓記事一覧に採用するセクション。PaperMod では推奨
mainSections = ["posts"]
paginate     = 10